import { mkdir, readFile, writeFile, readdir } from "node:fs/promises";

const htmlPath = new URL("./src/index.html", import.meta.url);
const cssPath = new URL("./src/admin.css", import.meta.url);
const jsDir = new URL("./src/js/", import.meta.url);
const libDir = new URL("./src/lib/", import.meta.url);
const jszipPath = new URL("./node_modules/jszip/dist/jszip.min.js", import.meta.url);
const generatedJsPath = new URL("./src/admin.js", import.meta.url);
const outPath = new URL("./admin.html", import.meta.url);
const docsDir = new URL("./docs/", import.meta.url);
const docsOutPath = new URL("./docs/index.html", import.meta.url);

const SHARED_UTILITY_MODULES = Object.freeze({
  "00-api-utils.js": {
    lib: "github-api-utils.mjs",
    global: "GitHubApiUtils"
  },
  "00-connect-utils.js": {
    lib: "connect-utils.mjs",
    global: "ConnectUtils"
  },
  "00-content-source-utils.js": {
    lib: "content-source-utils.mjs",
    global: "ContentSourceUtils"
  },
  "00-dirty-state.js": {
    lib: "dirty-state.mjs",
    global: "DirtyState"
  },
  "01-fragment-parser.js": {
    lib: "fragment-parser.mjs",
    global: "FragmentParser"
  },
  "01-github-errors.js": {
    lib: "github-errors.mjs",
    global: "GitHubErrors"
  },
  "01-validation-core.js": {
    lib: "validation.mjs",
    global: "Validation"
  },
  "02-config-utils.js": {
    lib: "config-utils.mjs",
    global: "ConfigUtils"
  },
  "04-preview-paths.js": {
    lib: "preview-paths.mjs",
    global: "PreviewPaths"
  },
  "07-editor-utils.js": {
    lib: "editor-utils.mjs",
    global: "EditorUtils"
  },
  "08-media-utils.js": {
    lib: "media-utils.mjs",
    global: "MediaUtils"
  },
  "10-publish-utils.js": {
    lib: "publish-utils.mjs",
    global: "PublishUtils"
  },
  "12-diagnostics-utils.js": {
    lib: "diagnostics-utils.mjs",
    global: "DiagnosticsUtils"
  }
});

const [html, css, jsFiles, jszipSrc] = await Promise.all([
  readFile(htmlPath, "utf8"),
  readFile(cssPath, "utf8"),
  readdir(jsDir),
  readFile(jszipPath, "utf8")
]);

function exportedNames(source) {
  const names = [];
  for (const match of source.matchAll(/export\s+(?:function|const)\s+([A-Za-z0-9_]+)/g)) {
    names.push(match[1]);
  }
  return names;
}

function stripEsmForBrowserSharedUtil(source) {
  return String(source || "")
    .replace(/^import\s+[^;]+;\s*$/gm, "")
    .replace(/\bexport\s+function\s+/g, "function ")
    .replace(/\bexport\s+const\s+/g, "const ")
    .trim();
}

async function sharedUtilitySource(fileName) {
  const spec = SHARED_UTILITY_MODULES[fileName];
  const source = await readFile(new URL(spec.lib, libDir), "utf8");
  const names = exportedNames(source);
  const body = stripEsmForBrowserSharedUtil(source);

  if (names.length === 1 && names[0] === spec.global) {
    return `/* Generated from src/lib/${spec.lib}. Do not edit this virtual browser module. */
const ${spec.global} = (() => {
${body}
  return ${spec.global};
})();`;
  }

  return `/* Generated from src/lib/${spec.lib}. Do not edit this virtual browser module. */
const ${spec.global} = (() => {
${body}

  return Object.freeze({
${names.map((name) => `    ${name}`).join(",\n")}
  });
})();`;
}

async function jsSourceFor(fileName) {
  if (SHARED_UTILITY_MODULES[fileName]) return sharedUtilitySource(fileName);
  return readFile(new URL(fileName, jsDir), "utf8");
}

async function maybeEsbuildTransform(jsRaw) {
  try {
    const esbuild = await import("esbuild");
    const result = await esbuild.transform(jsRaw, {
      target: "es2020",
      format: "default",
      minify: false,
      legalComments: "none"
    });
    return {
      code: result.code,
      usedEsbuild: true
    };
  } catch (error) {
    // Local artifact generation may run before npm install. CI/dev installs
    // esbuild from package.json and will use the esbuild path.
    console.warn("esbuild not available; using unbundled generated JS fallback.");
    return {
      code: jsRaw,
      usedEsbuild: false
    };
  }
}

const orderedJsFiles = [
  ...new Set([
    ...Object.keys(SHARED_UTILITY_MODULES),
    ...jsFiles.filter((name) => name.endsWith(".js"))
  ])
].sort();

const moduleSources = await Promise.all(orderedJsFiles.map((name) => jsSourceFor(name)));

const jsRaw = `/*
  GitCMS Admin JS — generated from src/js/*.js and src/lib/*.mjs.

  Shared utility modules are generated from src/lib/*.mjs so browser and tests
  use the same source of truth.

  Do not edit this file directly.
  Edit files in src/js/ or src/lib/ and run:
    node build-admin.mjs
*/

${moduleSources.map((s) => s.trim()).join("\n\n")}`;

const transformed = await maybeEsbuildTransform(jsRaw);

await writeFile(generatedJsPath, transformed.code.trim() + "\n", "utf8");

// Prevent literal closing script tags inside JavaScript strings/comments from
// terminating the inline script element in the built single-file admin.
const js = transformed.code.replaceAll("</script", "<\\/script");
const jszip = jszipSrc.replaceAll("</script", "<\\/script");

const built = html
  .replace(
    /<link\s+rel=["']stylesheet["']\s+href=["']\.\/admin\.css["']\s*\/?>/i,
    () => `<style>\n${css.trim()}\n</style>`
  )
  .replace(
    /<script\s+src=["']\.\/admin\.js["']\s+defer\s*><\/script>/i,
    () => `<script>\n${jszip.trim()}\n</script>\n<script>\n${js.trim()}\n</script>`
  );

if (built.includes('href="./admin.css"') || built.includes("href='./admin.css'")) {
  throw new Error("Build failed to inline admin.css into admin.html");
}

if (built.includes('src="./admin.js"') || built.includes("src='./admin.js'")) {
  throw new Error("Build failed to inline admin.js into admin.html");
}

await writeFile(outPath, built + "\n", "utf8");
await mkdir(docsDir, { recursive: true });
await writeFile(docsOutPath, built + "\n", "utf8");

console.log(
  `Built admin.html and docs/index.html from ${orderedJsFiles.length} JS modules` +
    (transformed.usedEsbuild ? " using esbuild" : " using fallback transform")
);
