import { mkdir, readFile, writeFile, readdir } from "node:fs/promises";

const htmlPath = new URL("./src/index.html", import.meta.url);
const cssPath = new URL("./src/admin.css", import.meta.url);
const jsDir = new URL("./src/js/", import.meta.url);
const generatedJsPath = new URL("./src/admin.js", import.meta.url);
const outPath = new URL("./admin.html", import.meta.url);
const docsDir = new URL("./docs/", import.meta.url);
const docsOutPath = new URL("./docs/admin.html", import.meta.url);

const [html, css, jsFiles] = await Promise.all([
  readFile(htmlPath, "utf8"),
  readFile(cssPath, "utf8"),
  readdir(jsDir)
]);

const orderedJsFiles = jsFiles
  .filter(name => name.endsWith(".js"))
  .sort();

const moduleSources = await Promise.all(
  orderedJsFiles.map(name => readFile(new URL(name, jsDir), "utf8"))
);

const jsRaw = `/*
  GitCMS Admin JS — generated from src/js/*.js.

  Do not edit this file directly.
  Edit files in src/js/ and run:
    node build-admin.mjs
*/

${moduleSources.map(s => s.trim()).join("\n\n")}`;

await writeFile(generatedJsPath, jsRaw + "\n", "utf8");

// Prevent literal closing script tags inside JavaScript strings/comments from
// terminating the inline script element in the built single-file admin.
const js = jsRaw.replaceAll("</script", "<\\/script");

const built = html
  .replace(
    /<link\s+rel=["']stylesheet["']\s+href=["']\.\/admin\.css["']\s*\/?>/i,
    () => `<style>\n${css.trim()}\n</style>`
  )
  .replace(
    /<script\s+src=["']\.\/admin\.js["']\s+defer\s*><\/script>/i,
    () => `<script>\n${js.trim()}\n</script>`
  );

if (built.includes('href="./admin.css"') || built.includes("href='./admin.css'")) {
  throw new Error('Build failed to inline admin.css into admin.html');
}

if (built.includes('src="./admin.js"') || built.includes("src='./admin.js'")) {
  throw new Error('Build failed to inline admin.js into admin.html');
}

await writeFile(outPath, built + "\n", "utf8");
await mkdir(docsDir, { recursive: true });
await writeFile(docsOutPath, built + "\n", "utf8");

console.log(`Built admin.html and docs/admin.html from ${orderedJsFiles.length} JS modules`);
